# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='data.proto',
  package='onlineproto',
  serialized_pb='\n\ndata.proto\x12\x0bonlineproto\"/\n\rplayer_data_t\x12\x0e\n\x06userid\x18\x01 \x02(\r\x12\x0e\n\x06status\x18\x02 \x02(\r\"\x87\x01\n\x0broom_data_t\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0f\n\x07ownerid\x18\x02 \x02(\r\x12\r\n\x05mapid\x18\x03 \x02(\r\x12\x0e\n\x06status\x18\x04 \x02(\r\x12,\n\x08playlist\x18\x05 \x03(\x0b\x32\x1a.onlineproto.player_data_t\x12\x0e\n\x06passwd\x18\x06 \x01(\r')




_PLAYER_DATA_T = descriptor.Descriptor(
  name='player_data_t',
  full_name='onlineproto.player_data_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userid', full_name='onlineproto.player_data_t.userid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='onlineproto.player_data_t.status', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=74,
)


_ROOM_DATA_T = descriptor.Descriptor(
  name='room_data_t',
  full_name='onlineproto.room_data_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='onlineproto.room_data_t.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ownerid', full_name='onlineproto.room_data_t.ownerid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mapid', full_name='onlineproto.room_data_t.mapid', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='onlineproto.room_data_t.status', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='playlist', full_name='onlineproto.room_data_t.playlist', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='passwd', full_name='onlineproto.room_data_t.passwd', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=77,
  serialized_end=212,
)


_ROOM_DATA_T.fields_by_name['playlist'].message_type = _PLAYER_DATA_T

class player_data_t(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYER_DATA_T
  
  # @@protoc_insertion_point(class_scope:onlineproto.player_data_t)

class room_data_t(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROOM_DATA_T
  
  # @@protoc_insertion_point(class_scope:onlineproto.room_data_t)

# @@protoc_insertion_point(module_scope)
