# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='login.proto',
  package='onlineproto',
  serialized_pb='\n\x0blogin.proto\x12\x0bonlineproto\"!\n\x0f\x63s_enter_server\x12\x0e\n\x06userid\x18\x01 \x02(\r\"!\n\x0fsc_enter_server\x12\x0e\n\x06userid\x18\x01 \x02(\r')




_CS_ENTER_SERVER = descriptor.Descriptor(
  name='cs_enter_server',
  full_name='onlineproto.cs_enter_server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userid', full_name='onlineproto.cs_enter_server.userid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=61,
)


_SC_ENTER_SERVER = descriptor.Descriptor(
  name='sc_enter_server',
  full_name='onlineproto.sc_enter_server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userid', full_name='onlineproto.sc_enter_server.userid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=63,
  serialized_end=96,
)



class cs_enter_server(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CS_ENTER_SERVER
  
  # @@protoc_insertion_point(class_scope:onlineproto.cs_enter_server)

class sc_enter_server(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SC_ENTER_SERVER
  
  # @@protoc_insertion_point(class_scope:onlineproto.sc_enter_server)

# @@protoc_insertion_point(module_scope)
