# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='online.proto',
  package='onlineproto',
  serialized_pb='\n\x0conline.proto\x12\x0bonlineproto\"\x1c\n\x0c\x63s_keep_live\x12\x0c\n\x04time\x18\x01 \x02(\r\"1\n\x0csc_keep_live\x12\x0c\n\x04time\x18\x01 \x02(\r\x12\x13\n\x0bserver_time\x18\x02 \x02(\r')




_CS_KEEP_LIVE = descriptor.Descriptor(
  name='cs_keep_live',
  full_name='onlineproto.cs_keep_live',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='onlineproto.cs_keep_live.time', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=57,
)


_SC_KEEP_LIVE = descriptor.Descriptor(
  name='sc_keep_live',
  full_name='onlineproto.sc_keep_live',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='onlineproto.sc_keep_live.time', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='server_time', full_name='onlineproto.sc_keep_live.server_time', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=108,
)



class cs_keep_live(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CS_KEEP_LIVE
  
  # @@protoc_insertion_point(class_scope:onlineproto.cs_keep_live)

class sc_keep_live(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SC_KEEP_LIVE
  
  # @@protoc_insertion_point(class_scope:onlineproto.sc_keep_live)

# @@protoc_insertion_point(module_scope)
