// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

#ifndef PROTOBUF_data_2eproto__INCLUDED
#define PROTOBUF_data_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace onlineproto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_data_2eproto();
void protobuf_AssignDesc_data_2eproto();
void protobuf_ShutdownFile_data_2eproto();

class player_data_t;
class room_data_t;

// ===================================================================

class player_data_t : public ::google::protobuf::Message {
 public:
  player_data_t();
  virtual ~player_data_t();
  
  player_data_t(const player_data_t& from);
  
  inline player_data_t& operator=(const player_data_t& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const player_data_t& default_instance();
  
  void Swap(player_data_t* other);
  
  // implements Message ----------------------------------------------
  
  player_data_t* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const player_data_t& from);
  void MergeFrom(const player_data_t& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 usierid = 1;
  inline bool has_usierid() const;
  inline void clear_usierid();
  static const int kUsieridFieldNumber = 1;
  inline ::google::protobuf::uint32 usierid() const;
  inline void set_usierid(::google::protobuf::uint32 value);
  
  // required uint32 status = 2;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 2;
  inline ::google::protobuf::uint32 status() const;
  inline void set_status(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:onlineproto.player_data_t)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 usierid_;
  ::google::protobuf::uint32 status_;
  friend void  protobuf_AddDesc_data_2eproto();
  friend void protobuf_AssignDesc_data_2eproto();
  friend void protobuf_ShutdownFile_data_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static player_data_t* default_instance_;
};
// -------------------------------------------------------------------

class room_data_t : public ::google::protobuf::Message {
 public:
  room_data_t();
  virtual ~room_data_t();
  
  room_data_t(const room_data_t& from);
  
  inline room_data_t& operator=(const room_data_t& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const room_data_t& default_instance();
  
  void Swap(room_data_t* other);
  
  // implements Message ----------------------------------------------
  
  room_data_t* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const room_data_t& from);
  void MergeFrom(const room_data_t& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);
  
  // required uint32 ownerid = 2;
  inline bool has_ownerid() const;
  inline void clear_ownerid();
  static const int kOwneridFieldNumber = 2;
  inline ::google::protobuf::uint32 ownerid() const;
  inline void set_ownerid(::google::protobuf::uint32 value);
  
  // required uint32 mapid = 3;
  inline bool has_mapid() const;
  inline void clear_mapid();
  static const int kMapidFieldNumber = 3;
  inline ::google::protobuf::uint32 mapid() const;
  inline void set_mapid(::google::protobuf::uint32 value);
  
  // required uint32 status = 4;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 4;
  inline ::google::protobuf::uint32 status() const;
  inline void set_status(::google::protobuf::uint32 value);
  
  // repeated .onlineproto.player_data_t playlist = 5;
  inline int playlist_size() const;
  inline void clear_playlist();
  static const int kPlaylistFieldNumber = 5;
  inline const ::onlineproto::player_data_t& playlist(int index) const;
  inline ::onlineproto::player_data_t* mutable_playlist(int index);
  inline ::onlineproto::player_data_t* add_playlist();
  inline const ::google::protobuf::RepeatedPtrField< ::onlineproto::player_data_t >&
      playlist() const;
  inline ::google::protobuf::RepeatedPtrField< ::onlineproto::player_data_t >*
      mutable_playlist();
  
  // optional uint32 passwd = 6;
  inline bool has_passwd() const;
  inline void clear_passwd();
  static const int kPasswdFieldNumber = 6;
  inline ::google::protobuf::uint32 passwd() const;
  inline void set_passwd(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:onlineproto.room_data_t)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 ownerid_;
  ::google::protobuf::uint32 mapid_;
  ::google::protobuf::uint32 status_;
  ::google::protobuf::RepeatedPtrField< ::onlineproto::player_data_t > playlist_;
  ::google::protobuf::uint32 passwd_;
  friend void  protobuf_AddDesc_data_2eproto();
  friend void protobuf_AssignDesc_data_2eproto();
  friend void protobuf_ShutdownFile_data_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static room_data_t* default_instance_;
};
// ===================================================================


// ===================================================================

// player_data_t

// required uint32 usierid = 1;
inline bool player_data_t::has_usierid() const {
  return _has_bit(0);
}
inline void player_data_t::clear_usierid() {
  usierid_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 player_data_t::usierid() const {
  return usierid_;
}
inline void player_data_t::set_usierid(::google::protobuf::uint32 value) {
  _set_bit(0);
  usierid_ = value;
}

// required uint32 status = 2;
inline bool player_data_t::has_status() const {
  return _has_bit(1);
}
inline void player_data_t::clear_status() {
  status_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 player_data_t::status() const {
  return status_;
}
inline void player_data_t::set_status(::google::protobuf::uint32 value) {
  _set_bit(1);
  status_ = value;
}

// -------------------------------------------------------------------

// room_data_t

// required uint32 id = 1;
inline bool room_data_t::has_id() const {
  return _has_bit(0);
}
inline void room_data_t::clear_id() {
  id_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 room_data_t::id() const {
  return id_;
}
inline void room_data_t::set_id(::google::protobuf::uint32 value) {
  _set_bit(0);
  id_ = value;
}

// required uint32 ownerid = 2;
inline bool room_data_t::has_ownerid() const {
  return _has_bit(1);
}
inline void room_data_t::clear_ownerid() {
  ownerid_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 room_data_t::ownerid() const {
  return ownerid_;
}
inline void room_data_t::set_ownerid(::google::protobuf::uint32 value) {
  _set_bit(1);
  ownerid_ = value;
}

// required uint32 mapid = 3;
inline bool room_data_t::has_mapid() const {
  return _has_bit(2);
}
inline void room_data_t::clear_mapid() {
  mapid_ = 0u;
  _clear_bit(2);
}
inline ::google::protobuf::uint32 room_data_t::mapid() const {
  return mapid_;
}
inline void room_data_t::set_mapid(::google::protobuf::uint32 value) {
  _set_bit(2);
  mapid_ = value;
}

// required uint32 status = 4;
inline bool room_data_t::has_status() const {
  return _has_bit(3);
}
inline void room_data_t::clear_status() {
  status_ = 0u;
  _clear_bit(3);
}
inline ::google::protobuf::uint32 room_data_t::status() const {
  return status_;
}
inline void room_data_t::set_status(::google::protobuf::uint32 value) {
  _set_bit(3);
  status_ = value;
}

// repeated .onlineproto.player_data_t playlist = 5;
inline int room_data_t::playlist_size() const {
  return playlist_.size();
}
inline void room_data_t::clear_playlist() {
  playlist_.Clear();
}
inline const ::onlineproto::player_data_t& room_data_t::playlist(int index) const {
  return playlist_.Get(index);
}
inline ::onlineproto::player_data_t* room_data_t::mutable_playlist(int index) {
  return playlist_.Mutable(index);
}
inline ::onlineproto::player_data_t* room_data_t::add_playlist() {
  return playlist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::onlineproto::player_data_t >&
room_data_t::playlist() const {
  return playlist_;
}
inline ::google::protobuf::RepeatedPtrField< ::onlineproto::player_data_t >*
room_data_t::mutable_playlist() {
  return &playlist_;
}

// optional uint32 passwd = 6;
inline bool room_data_t::has_passwd() const {
  return _has_bit(5);
}
inline void room_data_t::clear_passwd() {
  passwd_ = 0u;
  _clear_bit(5);
}
inline ::google::protobuf::uint32 room_data_t::passwd() const {
  return passwd_;
}
inline void room_data_t::set_passwd(::google::protobuf::uint32 value) {
  _set_bit(5);
  passwd_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace onlineproto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_data_2eproto__INCLUDED
