// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: online.proto

#ifndef PROTOBUF_online_2eproto__INCLUDED
#define PROTOBUF_online_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace onlineproto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_online_2eproto();
void protobuf_AssignDesc_online_2eproto();
void protobuf_ShutdownFile_online_2eproto();

class cs_keep_live;
class sc_keep_live;

// ===================================================================

class cs_keep_live : public ::google::protobuf::Message {
 public:
  cs_keep_live();
  virtual ~cs_keep_live();
  
  cs_keep_live(const cs_keep_live& from);
  
  inline cs_keep_live& operator=(const cs_keep_live& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const cs_keep_live& default_instance();
  
  void Swap(cs_keep_live* other);
  
  // implements Message ----------------------------------------------
  
  cs_keep_live* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const cs_keep_live& from);
  void MergeFrom(const cs_keep_live& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline ::google::protobuf::uint32 time() const;
  inline void set_time(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:onlineproto.cs_keep_live)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 time_;
  friend void  protobuf_AddDesc_online_2eproto();
  friend void protobuf_AssignDesc_online_2eproto();
  friend void protobuf_ShutdownFile_online_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static cs_keep_live* default_instance_;
};
// -------------------------------------------------------------------

class sc_keep_live : public ::google::protobuf::Message {
 public:
  sc_keep_live();
  virtual ~sc_keep_live();
  
  sc_keep_live(const sc_keep_live& from);
  
  inline sc_keep_live& operator=(const sc_keep_live& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const sc_keep_live& default_instance();
  
  void Swap(sc_keep_live* other);
  
  // implements Message ----------------------------------------------
  
  sc_keep_live* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const sc_keep_live& from);
  void MergeFrom(const sc_keep_live& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline ::google::protobuf::uint32 time() const;
  inline void set_time(::google::protobuf::uint32 value);
  
  // required uint32 server_time = 2;
  inline bool has_server_time() const;
  inline void clear_server_time();
  static const int kServerTimeFieldNumber = 2;
  inline ::google::protobuf::uint32 server_time() const;
  inline void set_server_time(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:onlineproto.sc_keep_live)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 time_;
  ::google::protobuf::uint32 server_time_;
  friend void  protobuf_AddDesc_online_2eproto();
  friend void protobuf_AssignDesc_online_2eproto();
  friend void protobuf_ShutdownFile_online_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static sc_keep_live* default_instance_;
};
// ===================================================================


// ===================================================================

// cs_keep_live

// required uint32 time = 1;
inline bool cs_keep_live::has_time() const {
  return _has_bit(0);
}
inline void cs_keep_live::clear_time() {
  time_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 cs_keep_live::time() const {
  return time_;
}
inline void cs_keep_live::set_time(::google::protobuf::uint32 value) {
  _set_bit(0);
  time_ = value;
}

// -------------------------------------------------------------------

// sc_keep_live

// required uint32 time = 1;
inline bool sc_keep_live::has_time() const {
  return _has_bit(0);
}
inline void sc_keep_live::clear_time() {
  time_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 sc_keep_live::time() const {
  return time_;
}
inline void sc_keep_live::set_time(::google::protobuf::uint32 value) {
  _set_bit(0);
  time_ = value;
}

// required uint32 server_time = 2;
inline bool sc_keep_live::has_server_time() const {
  return _has_bit(1);
}
inline void sc_keep_live::clear_server_time() {
  server_time_ = 0u;
  _clear_bit(1);
}
inline ::google::protobuf::uint32 sc_keep_live::server_time() const {
  return server_time_;
}
inline void sc_keep_live::set_server_time(::google::protobuf::uint32 value) {
  _set_bit(1);
  server_time_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace onlineproto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_online_2eproto__INCLUDED
